# Generated by Django 4.0.1 on 2022-09-13 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBanda', models.CharField(max_length=200, verbose_name='Nombre')),
                ('imgBanda', models.ImageField(null=True, upload_to='bandas', verbose_name='Imagen Banda')),
                ('descripBanda', models.TextField(null=True, verbose_name='Descripción')),
                ('link_sptf', models.URLField(blank=True, null=True, verbose_name='Link Spotify')),
                ('link_apple', models.URLField(blank=True, null=True, verbose_name='Link Apple Music')),
                ('link_ytb', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('link_ig', models.URLField(blank=True, null=True, verbose_name='Link Instagram')),
                ('link_fb', models.URLField(blank=True, null=True, verbose_name='Link Facebook')),
                ('link_tw', models.URLField(blank=True, null=True, verbose_name='Link Twitter')),
            ],
            options={
                'verbose_name': 'banda',
                'verbose_name_plural': 'bandas',
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('caratula', models.ImageField(null=True, upload_to='catalogo', verbose_name='Carátula')),
                ('fechaDisco', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('descripDisco', models.TextField(null=True, verbose_name='Descripción')),
                ('link_sptf', models.TextField(max_length=300, null=True, verbose_name='Código inserción desde Spotify')),
                ('link_apple', models.URLField(blank=True, null=True, verbose_name='Link Apple Music')),
                ('link_ytb', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('link_tienda_cd', models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional CD')),
                ('link_tienda_vin', models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional VINILO')),
                ('link_tienda_cas', models.URLField(blank=True, null=True, verbose_name='Link Tienda Nacional CASSETTE')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.banda', verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'disco',
                'verbose_name_plural': 'discos',
            },
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArt', models.CharField(max_length=200, verbose_name='Nombre Artístico')),
                ('nombreReal', models.CharField(max_length=200, null=True, verbose_name='Nombre Real')),
                ('imgMusico', models.ImageField(null=True, upload_to='musicos', verbose_name='Imagen Músico')),
                ('link_ig', models.URLField(blank=True, null=True, verbose_name='Link Instagram')),
                ('link_fb', models.URLField(blank=True, null=True, verbose_name='Link Facebook')),
                ('link_tw', models.URLField(blank=True, null=True, verbose_name='Link Twitter')),
            ],
            options={
                'verbose_name': 'Músico',
                'verbose_name_plural': 'Músicos',
            },
        ),
        migrations.CreateModel(
            name='ProduccionDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Producción Musical'), (2, 'Edición y Mezcla'), (3, 'Masterización'), (4, 'Músico invitado'), (5, 'Otro')], verbose_name='Rol en la Producción')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción de la colaboración')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.disco', verbose_name='Disco')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.musico', verbose_name='Músico')),
            ],
            options={
                'order_with_respect_to': 'disco',
                'unique_together': {('disco', 'musico')},
            },
        ),
        migrations.CreateModel(
            name='IntegranteBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Voz'), (2, 'Bateria'), (3, 'Bajo'), (4, 'Guitarra'), (5, 'Teclado/Piano'), (6, 'Vientos'), (7, 'Cuerdas'), (5, 'Otro')], verbose_name='Rol en la Banda')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo actualmente')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.banda', verbose_name='Banda')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.musico', verbose_name='Músico')),
            ],
            options={
                'order_with_respect_to': 'banda',
                'unique_together': {('banda', 'musico')},
            },
        ),
    ]
