# Generated by Django 4.0.1 on 2022-05-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nosotros',
            new_name='Acercade',
        ),
    ]
