# Generated by Django 4.0.1 on 2022-05-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_nosotros_acercade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acercade',
            new_name='Nosotro',
        ),
    ]
