# Generated by Django 4.0.1 on 2022-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_acercade_nosotro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nosotro',
            new_name='Nosotros',
        ),
    ]
