# Generated by Django 4.0.1 on 2022-05-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_nosotro_nosotros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name': 'Nosotros', 'verbose_name_plural': 'Nosotros'},
        ),
    ]
