# Generated by Django 4.0.1 on 2022-05-11 21:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_nosotros_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
